#!/usr/bin/env python
"""Bake island A out of the retired world artifact, as RLE, for 00c_worldgen.js.

WHY ISLAND A IS BAKED AND NOT GENERATED. It is the starter island: four provinces, the landing beach,
the Cairnworks, the bridge head, and every hand-placed pillar and arrival tile that a new player's
first twenty levels run through. It has been walked, screenshotted and tuned. A generator that
reproduced it "closely" would silently move a spawn point or narrow a beach, and the only way anyone
would find out is a player falling through a gap. So island A is preserved EXACTLY -- as bytes -- and
only the world east of the bridge is generated.

WHY RLE. The artifact this replaces is 839 KB of JSON, downloaded by every player on every code-cache
bump. Island A's own bbox is ~127k tiles; run-length encoded over the tile alphabet it is a fraction
of that, and it is the only baked data the generator needs.

    py tools/bake_island_a.py            # prints the JS constant, and writes it into 00c_worldgen.js
    py tools/bake_island_a.py --print    # print only

THE ARTIFACT THIS READS HAS BEEN DELETED, and that is deliberate: ISLE_A_RLE in 00c_worldgen.js is the
authority for island A now, and keeping an 839 KB file around that says the same thing in a different
format is how the two drift apart. This script is kept because it records HOW that constant was
derived, and because the derivation may need repeating. To run it, restore its input first:

    git log --diff-filter=D --name-only -- 00d_vgrove.js     # find the commit that removed it
    git show <that commit>^:00d_vgrove.js > 00d_vgrove.js

FORMAT. One string per row, runs as "<char><count>" with the count omitted when it is 1. Rows are
joined with '|'. A trailing water run is dropped -- the decoder fills water first -- which is most of
the saving. The decoder is eight lines; see rleRows() in 00c_worldgen.js.
"""

import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, '00d_vgrove.js')
DEST = os.path.join(ROOT, '00c_worldgen.js')

# The bridge's western end. Everything left of it is island A; the bridge itself and everything east
# is generated. Read from the artifact's own rings.bridge so this cannot disagree with the world.
def load():
    s = io.open(SRC, encoding='utf-8').read()
    i = s.index('{', s.index('ROOM_DEFS'))
    return json.loads(s[i:s.rindex('}') + 1])


def rle_row(row):
    out = []
    for m in re.finditer(r'(.)\1*', row):
        ch, n = m.group(1), len(m.group(0))
        out.append(ch if n == 1 else '%s%d' % (ch, n))
    s = ''.join(out)
    # drop a trailing water run: the decoder starts every row as water
    return re.sub(r'w\d*$', '', s)


def main():
    d = load()
    W, H = d['w'], d['h']
    x1 = d['rings']['bridge']['x0']          # island A owns everything strictly left of the bridge
    rows = d['map']
    assert len(rows) == H and len(rows[0]) == W, 'artifact is not %dx%d' % (W, H)

    # measure the real footprint, so the constant records what it covers rather than asserting it
    land = 0
    minx, maxx, miny, maxy = W, -1, H, -1
    for y, row in enumerate(rows):
        for x in range(x1):
            if row[x] != 'w':
                land += 1
                minx = min(minx, x); maxx = max(maxx, x)
                miny = min(miny, y); maxy = max(maxy, y)
    enc = '|'.join(rle_row(row[:x1]) for row in rows)

    print('island A: x < %d, %d land tiles, bbox %d,%d..%d,%d (%dx%d)'
          % (x1, land, minx, miny, maxx, maxy, maxx - minx + 1, maxy - miny + 1))
    print('RLE: %d chars (raw slice would be %d)' % (len(enc), H * x1))

    js = ('// %d land tiles, bbox %d,%d..%d,%d. Generated by tools/bake_island_a.py from the retired\n'
          '// 00d_vgrove.js artifact -- see that script for why this half of the world is bytes and\n'
          '// not a generator. Runs are "<char><count>", count omitted at 1, rows joined with "|",\n'
          '// trailing water dropped because the decoder fills water first.\n'
          'const ISLE_A_W = %d;\n'
          'const ISLE_A_RLE = %s;\n'
          % (land, minx, miny, maxx, maxy, x1, json.dumps(enc)))

    if '--print' in sys.argv or not os.path.exists(DEST):
        io.open(os.path.join(ROOT, '_isle_a.js'), 'w', encoding='utf-8').write(js)
        print('wrote _isle_a.js (%d bytes)' % len(js))
        return

    s = io.open(DEST, encoding='utf-8').read()
    # ANCHOR THE END OF THE MATCH TO THE END OF ITS OWN LINE. This was `.*?;\n` under DOTALL, which
    # looks non-greedy and safe and is not: on the placeholder line `const ISLE_A_RLE = '';   //
    # replaced by ...` the semicolon is followed by a comment, so the first `;\n` the pattern could
    # find was the NEXT statement's -- and the replacement silently ate `const WG_W = 1160`. The file
    # then failed with "WG_W is not defined" from inside genWorld, forty lines from the real cause.
    # `.*$` is not "to the end of the line" under DOTALL -- `.` matches newlines, so it ran greedily
    # to the end of the FILE and the assert below caught it. [^\n]* is what "rest of this line" means.
    m = re.search(r'(?ms)^// \d+ land tiles, bbox.*?^const ISLE_A_RLE = [^\n]*', s)
    if not m:
        sys.exit('no ISLE_A_RLE block in 00c_worldgen.js to replace -- run with --print first')
    assert 'const WG_W' not in m.group(0), 'the match overran into the world spec -- refusing'
    out = s[:m.start()] + js.rstrip('\n') + s[m.end():]
    io.open(DEST, 'w', encoding='utf-8', newline='').write(out)
    print('replaced the ISLE_A_RLE block in 00c_worldgen.js')


if __name__ == '__main__':
    main()
