#!/usr/bin/env python
"""Prove the Sprite Lab's preview matches the file spritegen would write. Pixel for pixel.

WHY THIS IS THE TEST THAT MATTERS. The lab's entire value is that you tune against what ships. Every
op in _spritelab.js is a hand port of the op of the same name in spritegen.py, and a hand port is
exactly the kind of thing that drifts silently: a rounding rule, a saturation floor, the order of two
clamps. Nothing on screen would look wrong -- it would just no longer be the thing the tool writes,
and you would tune a ramp against one image and ship another.

So this runs the SAME op chains through both, and compares the resulting RGBA bytes.

It is also why spritegen no longer uses PIL's GaussianBlur or MaxFilter. Those are one line each and
perfectly correct, but a browser cannot reproduce Pillow's Gaussian, and canvas's own `filter:blur()`
is a different Gaussian again -- so `glow` could never have matched. Both kernels are written out in
spritegen.py now (blur radius r == three edge-clamped box passes of window 2r+1, each way) and this
check is what keeps the two copies honest.

HOW. A generated page loads _spritelab.js, runs the chains in the browser via the `window.spritelab`
handle the lab exposes, and prints the result as base64 into the DOM. Chrome is found and driven the
same way tools/selftest.py does it -- headless, --dump-dom, no CDP and no node.

    py tools/serve.py             # in another shell, or nothing loads
    py tools/labparity.py         # -> PASS / FAIL per chain, and the worst pixel delta

Interpreter is Python312 by full path; `py` is broken on this machine.
"""

import base64
import io
import json
import os
import re
import subprocess
import sys

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import spritegen as S
from selftest import find_chrome, fresh_profile

PORT = 10500
PAGE = os.path.join(ROOT, "_labparity.html")

# One chain per op that can differ, plus the shipped elements. `layer` is left out: it resolves a
# second file off disk at build time and the lab only previews it when that source is already
# loaded, so the two are not meant to agree without a source picked.
CASES = [
    ("hue-to",    "assets/mobs/arch_golem.png", [{"op": "hue", "to": 200}]),
    ("hue-band",  "assets/mobs/arch_golem.png", [{"op": "hue", "to": 205, "only": [265, 305]}]),
    ("hue-by",    "assets/mobs/arch_husk.png",  [{"op": "hue", "by": 90}]),
    ("sat",       "assets/mobs/arch_husk.png",  [{"op": "sat", "mul": 1.4, "add": -0.05}]),
    ("light",     "assets/mobs/arch_plant.png", [{"op": "light", "mul": 0.8, "add": 0.05}]),
    ("ramp",      "assets/mobs/arch_golem.png",
     [{"op": "ramp", "shadow": "#16223a", "high": "#bfe6ff", "span": 0.78, "mix": 0.58}]),
    ("tint",      "assets/mobs/arch_crab.png",  [{"op": "tint", "color": "#2a1840", "amount": 0.34}]),
    ("alpha",     "assets/mobs/arch_wisp.png",  [{"op": "alpha", "mul": 0.62}]),
    ("outline",   "assets/mobs/arch_golem.png",
     [{"op": "pad", "amount": 6}, {"op": "outline", "color": "#ffd76a", "width": 1, "alpha": 210}]),
    ("glow-hue",  "assets/mobs/arch_golem.png", [{"op": "glow", "hue": 275, "radius": 5, "strength": 0.34}]),
    ("glow-col",  "assets/mobs/arch_golem.png",
     [{"op": "pad", "amount": 6}, {"op": "glow", "color": "#ffb02e", "radius": 5, "strength": 0.5}]),
    ("scale",     "assets/mobs/arch_bird.png",  [{"op": "scale", "factor": 2}]),
    ("flip",      "assets/mobs/arch_bird.png",  [{"op": "flip"}]),
    ("element-frost",  "assets/mobs/arch_golem.png",
     [{"op": "ramp", "shadow": "#16223a", "high": "#bfe6ff", "span": 0.78, "mix": 0.58},
      {"op": "sat", "mul": 0.95}]),
    ("element-shadow", "assets/mobs/arch_husk.png",
     [{"op": "ramp", "shadow": "#140f20", "high": "#8f7ec2", "span": 0.72, "mix": 0.68},
      {"op": "sat", "mul": 0.75}, {"op": "glow", "hue": 275, "radius": 5, "strength": 0.34}]),
    ("element-elite",  "assets/mobs/arch_golem.png",
     [{"op": "pad", "amount": 6}, {"op": "sat", "mul": 1.12},
      {"op": "outline", "color": "#ffd76a", "width": 1, "alpha": 210},
      {"op": "glow", "color": "#ffb02e", "radius": 5, "strength": 0.5}]),
]

HTML = """<!doctype html>
<!-- generated by tools/labparity.py; never edit, never commit -->
<html><head><meta charset="utf-8"><title>lab parity</title></head><body>
<pre id="out">running</pre>
<script src="_spritelab.js?v=%%CACHEBUST%%"></script>
<script>
const CASES = %s;
(async () => {
  const lines = [];
  try {
    const L = window.spritelab;
    if(!L) throw new Error('window.spritelab missing -- did _spritelab.js load?');
    for(const c of CASES){
      const src = await L.loadImage(c.src);
      // The lab measures the set's reference hue once, off the first frame. Same here.
      const cache = {};
      const ctx = { setHue: L.domHue(src.d, null),
                    bandHue: only => { const k=String(only);
                      if(!(k in cache)) cache[k]=L.domHue(src.d, only); return cache[k]; },
                    layers: {} };
      const out = L.applyOps(src, c.ops, ctx);
      const cv = document.createElement('canvas');
      cv.width = out.w; cv.height = out.h;
      cv.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(out.d), out.w, out.h), 0, 0);
      // Raw bytes, not the PNG: we are comparing pixels, and two encoders need not agree on bytes.
      let b = '';
      for(let i=0;i<out.d.length;i++) b += String.fromCharCode(out.d[i]);
      lines.push(c.name + '\\t' + out.w + '\\t' + out.h + '\\t' + btoa(b));
    }
  } catch(e){ lines.push('ERROR\\t' + (e && e.message)); }
  document.getElementById('out').textContent = lines.join('\\n');
})();
</script></body></html>
"""


def build_page():
    cases = [{"name": n, "src": s, "ops": o} for n, s, o in CASES]
    # Cache-busted on the lab's own mtime. serve.py sends no-store and headless gets a fresh profile,
    # yet an edit to _spritelab.js still came back stale once here -- and a parity check that silently
    # tests the PREVIOUS version of the file is worse than no parity check, because it reports PASS.
    stamp = str(int(os.path.getmtime(os.path.join(ROOT, "_spritelab.js"))))
    # Substitute AFTER the %-formatting, and match the single-% form. The template carries
    # `%%CACHEBUST%%` because it has to survive `HTML % ...`, which turns it into `%CACHEBUST%` --
    # so replacing the doubled form here found nothing and every run shipped the literal token.
    body = (HTML % json.dumps(cases)).replace("%CACHEBUST%", stamp)
    with io.open(PAGE, "w", encoding="utf-8") as f:
        f.write(body)
    return PAGE


def py_result(src, ops):
    # load_rgba, not a raw open: it zeroes the colour under fully transparent pixels, which is what a
    # canvas hands back and what the ops on both sides are therefore comparing.
    ref = S.load_rgba(os.path.join(ROOT, src))
    cache = {}

    def band_hue(band):
        if band not in cache:
            cache[band] = S.dom_hue(ref, only=band)
        return cache[band]

    ctx = {"name": os.path.basename(src), "set_hue": S.dom_hue(ref), "set": "parity",
           "band_hue": band_hue}
    return S.apply_ops(ref.copy(), ops, ctx)


def main():
    build_page()
    chrome = find_chrome()
    cmd = [chrome, "--headless=new", "--disable-gpu",
           "--user-data-dir=" + fresh_profile("labparity"),
           "--virtual-time-budget=40000", "--dump-dom"]
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        cmd.append("--no-sandbox")
    cmd.append("http://127.0.0.1:%d/%s" % (PORT, os.path.basename(PAGE)))
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    dom = proc.stdout.decode("utf-8", "replace")
    m = re.search(r'(?s)<pre id="out"[^>]*>(.*?)</pre>', dom)
    if not m:
        sys.exit("no #out in the dumped DOM -- is tools/serve.py running on %d? (%d bytes)"
                 % (PORT, len(dom)))
    body = m.group(1).strip()
    if body.startswith("ERROR") or body == "running":
        sys.exit("the lab failed in the browser: %s" % body[:300])

    got = {}
    for line in body.splitlines():
        parts = line.split("\t")
        if len(parts) != 4:
            continue
        name, w, h, b64 = parts
        raw = base64.b64decode(b64)
        got[name] = np.frombuffer(raw, dtype=np.uint8).reshape(int(h), int(w), 4)

    bad = 0
    for name, src, ops in CASES:
        want = py_result(src, ops)
        js = got.get(name)
        if js is None:
            print("  FAIL  %-16s the browser returned nothing" % name)
            bad += 1
            continue
        if js.shape != want.shape:
            print("  FAIL  %-16s shape %s in the lab, %s from the tool" % (name, js.shape, want.shape))
            bad += 1
            continue
        d = np.abs(js.astype(np.int16) - want.astype(np.int16))
        worst, n_off = int(d.max()), int((d > 0).sum())
        if worst == 0:
            print("  PASS  %-16s identical  (%d px)" % (name, want.shape[0] * want.shape[1]))
        else:
            print("  FAIL  %-16s worst channel delta %d over %d byte(s)" % (name, worst, n_off))
            # Name the actual pixels. "delta 1 somewhere" is not a lead; "these three pixels, this
            # channel, these two values" says immediately whether it is a rounding boundary or a
            # different code path.
            # Output coordinates and both output values -- deliberately NOT the source pixel at the
            # same coordinate. A chain containing `pad` or `scale` moves everything, so the source
            # pixel sharing an index with a failing output is a different pixel entirely; printing it
            # sent one debugging session looking at the wrong colour for a while.
            ys, xs, cs = np.nonzero(d)
            for k in range(min(4, len(ys))):
                y, x, c = int(ys[k]), int(xs[k]), int(cs[k])
                print("          out(%d,%d) %s: lab %d, tool %d"
                      % (x, y, "rgba"[c], js[y, x, c], want[y, x, c]))
            bad += 1

    print()
    print("RESULT %s  %d of %d chains identical" % ("FAIL" if bad else "PASS", len(CASES) - bad, len(CASES)))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
